import mongoose from 'mongoose'
import dotenv from 'dotenv'
import Product from './models/Product.js'

dotenv.config()

const products = [
  {
    name: "Opor prujina Cobalt",
    description: "Chevrolet Cobalt uchun zavod sifatida ishlab chiqarilgan opor prujina. 12 oy kafolat.",
    price: 35,
    oldPrice: 45,
    priceUZS: 437500,
    oldPriceUZS: 562500,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.9,
    reviews: 128,
    badge: "Bestseller",
    category: "opor",
    carModel: "Chevrolet Cobalt",
    stock: 200,
  },
  {
    name: "Opor prujina Malibu",
    description: "Chevrolet Malibu uchun yuqori sifatli opor prujina. Tebranishni kamaytiradi.",
    price: 42,
    oldPrice: null,
    priceUZS: 525000,
    oldPriceUZS: null,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.7,
    reviews: 87,
    badge: "Popular",
    category: "opor",
    carModel: "Chevrolet Malibu",
    stock: 150,
  },
  {
    name: "Opor prujina Spark",
    description: "Chevrolet Spark uchun arzon va sifatli opor prujina.",
    price: 28,
    oldPrice: 35,
    priceUZS: 350000,
    oldPriceUZS: 437500,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.6,
    reviews: 203,
    badge: null,
    category: "opor",
    carModel: "Chevrolet Spark",
    stock: 300,
  },
  {
    name: "Opor prujina Nexia 3",
    description: "Daewoo Nexia 3 uchun zavod standartidagi opor prujina.",
    price: 30,
    oldPrice: null,
    priceUZS: 375000,
    oldPriceUZS: null,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.5,
    reviews: 65,
    badge: "New",
    category: "opor",
    carModel: "Daewoo Nexia 3",
    stock: 180,
  },
  {
    name: "Tormoz kolodkasi Cobalt",
    description: "Chevrolet Cobalt old tormoz kolodkasi. Ceramic qoplama bilan.",
    price: 22,
    oldPrice: 28,
    priceUZS: 275000,
    oldPriceUZS: 350000,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.8,
    reviews: 156,
    badge: "Bestseller",
    category: "brake-pads",
    carModel: "Chevrolet Cobalt",
    stock: 250,
  },
  {
    name: "Tormoz kolodkasi Malibu",
    description: "Chevrolet Malibu uchun old tormoz kolodkasi. Yuqori samarali.",
    price: 28,
    oldPrice: null,
    priceUZS: 350000,
    oldPriceUZS: null,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.7,
    reviews: 98,
    badge: "Popular",
    category: "brake-pads",
    carModel: "Chevrolet Malibu",
    stock: 180,
  },
  {
    name: "Tormoz kolodkasi Spark",
    description: "Chevrolet Spark uchun arzon va ishonchli tormoz kolodkasi.",
    price: 18,
    oldPrice: 22,
    priceUZS: 225000,
    oldPriceUZS: 275000,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.5,
    reviews: 142,
    badge: null,
    category: "brake-pads",
    carModel: "Chevrolet Spark",
    stock: 320,
  },
  {
    name: "Tormoz kolodkasi Nexia 3",
    description: "Daewoo Nexia 3 uchun old tormoz kolodkasi. 12 oy kafolat.",
    price: 20,
    oldPrice: null,
    priceUZS: 250000,
    oldPriceUZS: null,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.6,
    reviews: 73,
    badge: "New",
    category: "brake-pads",
    carModel: "Daewoo Nexia 3",
    stock: 200,
  },
  {
    name: "Tormoz diski Cobalt",
    description: "Chevrolet Cobalt uchun old tormoz diski. Ventilyatsiyalangan.",
    price: 55,
    oldPrice: 70,
    priceUZS: 687500,
    oldPriceUZS: 875000,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.9,
    reviews: 95,
    badge: "Bestseller",
    category: "brake-discs",
    carModel: "Chevrolet Cobalt",
    stock: 120,
  },
  {
    name: "Tormoz diski Malibu",
    description: "Chevrolet Malibu uchun yuqori sifatli tormoz diski.",
    price: 65,
    oldPrice: null,
    priceUZS: 812500,
    oldPriceUZS: null,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.8,
    reviews: 67,
    badge: "Popular",
    category: "brake-discs",
    carModel: "Chevrolet Malibu",
    stock: 90,
  },
  {
    name: "Tormoz diski Spark",
    description: "Chevrolet Spark uchun arzon tormoz diski. Sifat kafolatlangan.",
    price: 40,
    oldPrice: 50,
    priceUZS: 500000,
    oldPriceUZS: 625000,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.5,
    reviews: 112,
    badge: null,
    category: "brake-discs",
    carModel: "Chevrolet Spark",
    stock: 160,
  },
  {
    name: "Tormoz diski Nexia 3",
    description: "Daewoo Nexia 3 uchun zavod sifatidagi tormoz diski.",
    price: 48,
    oldPrice: null,
    priceUZS: 600000,
    oldPriceUZS: null,
    currency: "$",
    currencyUZS: "so'm",
    image: "",
    rating: 4.7,
    reviews: 54,
    badge: "New",
    category: "brake-discs",
    carModel: "Daewoo Nexia 3",
    stock: 140,
  },
]

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('✅ MongoDB connected')

    await Product.deleteMany({})
    console.log('🗑️  Old products deleted')

    await Product.insertMany(products)
    console.log(`✅ ${products.length} products seeded`)

    await mongoose.disconnect()
    console.log('👋 Disconnected')
    process.exit(0)
  } catch (err) {
    console.error('❌ Seed failed:', err.message)
    process.exit(1)
  }
}

seed()
